"""initial migration

Revision ID: 5a55be2323e9
Revises: 
Create Date: 2026-02-25 20:53:14.733053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a55be2323e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_type', sa.Enum('CARDIO', 'WEIGHT_REPS', name='gymsettype'), nullable=False))
    op.drop_column('sets', 'set_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('set_type', postgresql.ENUM('CARDIO', 'WEIGHT_REPS', name='gymsettype'), autoincrement=False, nullable=False))
    op.drop_column('exercises', 'exercise_type')
    # ### end Alembic commands ###
