"""initial_schema

Revision ID: 8b0251763a97
Revises: 
Create Date: 2026-03-03 20:35:24.959847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0251763a97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=30), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('serving_size_text', sa.String(length=50), nullable=True),
    sa.Column('serving_quantity_g', sa.Float(), nullable=True),
    sa.Column('nutriscore', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('allergens', sa.String(length=300), nullable=True),
    sa.Column('energy_kcal_100g', sa.Float(), nullable=True),
    sa.Column('proteins_100g', sa.Float(), nullable=True),
    sa.Column('carbohydrates_100g', sa.Float(), nullable=True),
    sa.Column('sugars_100g', sa.Float(), nullable=True),
    sa.Column('fat_100g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_100g', sa.Float(), nullable=True),
    sa.Column('fiber_100g', sa.Float(), nullable=True),
    sa.Column('salt_100g', sa.Float(), nullable=True),
    sa.Column('sodium_100g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('off_raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='macro_tracker'
    )
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=True, schema='macro_tracker', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.create_index('ix_products_name', 'products', ['product_name'], unique=False, schema='macro_tracker')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True, schema='core')
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('account', sa.Enum('REVOLUT', 'IMAGIN', name='expensecategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='expenses_tracker'
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('expected', 'check_in', 'boarding', 'gate_closed', 'departed', 'en_route', 'approaching', 'delayed', 'arrived', 'canceled', 'diverted', 'canceled_uncertain', 'unknown', name='flightstatus', schema='flights_tracker'), nullable=False),
    sa.Column('origin_iata', sa.String(length=4), nullable=False),
    sa.Column('origin_icao', sa.String(length=5), nullable=True),
    sa.Column('origin_name', sa.String(length=200), nullable=True),
    sa.Column('origin_city', sa.String(length=100), nullable=True),
    sa.Column('origin_country_code', sa.String(length=3), nullable=True),
    sa.Column('origin_timezone', sa.String(length=50), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('destination_iata', sa.String(length=4), nullable=False),
    sa.Column('destination_icao', sa.String(length=5), nullable=True),
    sa.Column('destination_name', sa.String(length=200), nullable=True),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('destination_country_code', sa.String(length=3), nullable=True),
    sa.Column('destination_timezone', sa.String(length=50), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.Column('airline_iata', sa.String(length=3), nullable=True),
    sa.Column('airline_icao', sa.String(length=4), nullable=True),
    sa.Column('airline_name', sa.String(length=100), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revised_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revised_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('delay_departure_minutes', sa.Integer(), nullable=True),
    sa.Column('delay_arrival_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('aircraft_model', sa.String(length=100), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=20), nullable=True),
    sa.Column('aircraft_icao24', sa.String(length=10), nullable=True),
    sa.Column('terminal_origin', sa.String(length=10), nullable=True),
    sa.Column('gate_origin', sa.String(length=10), nullable=True),
    sa.Column('terminal_destination', sa.String(length=10), nullable=True),
    sa.Column('baggage_belt', sa.String(length=10), nullable=True),
    sa.Column('runway_origin', sa.String(length=10), nullable=True),
    sa.Column('runway_destination', sa.String(length=10), nullable=True),
    sa.Column('data_quality', sa.String(length=50), nullable=True),
    sa.Column('is_past', sa.Boolean(), nullable=False),
    sa.Column('is_diverted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'flight_number', 'flight_date'),
    schema='flights_tracker'
    )
    op.create_index('ix_flights_user_date', 'flights', ['user_id', 'flight_date'], unique=False, schema='flights_tracker')
    op.create_index('ix_flights_user_past', 'flights', ['user_id', 'is_past'], unique=False, schema='flights_tracker')
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gym_tracker'
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('total_sets', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gym_tracker'
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'other', name='mealtype', schema='macro_tracker'), nullable=False),
    sa.Column('amount_g', sa.Float(), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=True),
    sa.Column('proteins_g', sa.Float(), nullable=True),
    sa.Column('carbohydrates_g', sa.Float(), nullable=True),
    sa.Column('sugars_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('salt_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['macro_tracker.products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='macro_tracker'
    )
    op.create_index('ix_diary_user_date', 'diary_entries', ['user_id', 'entry_date'], unique=False, schema='macro_tracker')
    op.create_index('ix_diary_user_meal', 'diary_entries', ['user_id', 'entry_date', 'meal_type'], unique=False, schema='macro_tracker')
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('proteins_g', sa.Float(), nullable=False),
    sa.Column('carbohydrates_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_goals_user_id'),
    schema='macro_tracker'
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_photo_key', sa.String(length=500), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travels_tracker'
    )
    op.create_index(op.f('ix_travels_tracker_trips_user_id'), 'trips', ['user_id'], unique=False, schema='travels_tracker')
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('exercise_type', sa.Enum('CARDIO', 'WEIGHT_REPS', name='gymsettype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['gym_tracker.workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gym_tracker'
    )
    op.create_table('workout_muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'BICEPS', 'TRICEPS', 'CORE', 'ABS', 'SHOULDERS', 'LEGS', name='musclegroupcategory', schema='gym_tracker'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['gym_tracker.workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gym_tracker'
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('sightseeing', 'food', 'transport', 'accommodation', 'activity', 'other', name='activitycategory', schema='travels_tracker'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['travels_tracker.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travels_tracker'
    )
    op.create_index(op.f('ix_travels_tracker_activities_trip_id'), 'activities', ['trip_id'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_travels_tracker_activities_user_id'), 'activities', ['user_id'], unique=False, schema='travels_tracker')
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_photo_key', sa.String(length=500), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['travels_tracker.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travels_tracker'
    )
    op.create_index(op.f('ix_travels_tracker_albums_trip_id'), 'albums', ['trip_id'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_travels_tracker_albums_user_id'), 'albums', ['user_id'], unique=False, schema='travels_tracker')
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('incline_percent', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['gym_tracker.exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gym_tracker'
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'deleted', name='photostatus', schema='travels_tracker'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['travels_tracker.albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['travels_tracker.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travels_tracker'
    )
    op.create_index(op.f('ix_travels_tracker_photos_album_id'), 'photos', ['album_id'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_travels_tracker_photos_trip_id'), 'photos', ['trip_id'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_travels_tracker_photos_user_id'), 'photos', ['user_id'], unique=False, schema='travels_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travels_tracker_photos_user_id'), table_name='photos', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_tracker_photos_trip_id'), table_name='photos', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_tracker_photos_album_id'), table_name='photos', schema='travels_tracker')
    op.drop_table('photos', schema='travels_tracker')
    op.drop_table('sets', schema='gym_tracker')
    op.drop_index(op.f('ix_travels_tracker_albums_user_id'), table_name='albums', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_tracker_albums_trip_id'), table_name='albums', schema='travels_tracker')
    op.drop_table('albums', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_tracker_activities_user_id'), table_name='activities', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_tracker_activities_trip_id'), table_name='activities', schema='travels_tracker')
    op.drop_table('activities', schema='travels_tracker')
    op.drop_table('workout_muscle_groups', schema='gym_tracker')
    op.drop_table('exercises', schema='gym_tracker')
    op.drop_index(op.f('ix_travels_tracker_trips_user_id'), table_name='trips', schema='travels_tracker')
    op.drop_table('trips', schema='travels_tracker')
    op.drop_table('user_goals', schema='macro_tracker')
    op.drop_index('ix_diary_user_meal', table_name='diary_entries', schema='macro_tracker')
    op.drop_index('ix_diary_user_date', table_name='diary_entries', schema='macro_tracker')
    op.drop_table('diary_entries', schema='macro_tracker')
    op.drop_table('workouts', schema='gym_tracker')
    op.drop_table('body_measurements', schema='gym_tracker')
    op.drop_index('ix_flights_user_past', table_name='flights', schema='flights_tracker')
    op.drop_index('ix_flights_user_date', table_name='flights', schema='flights_tracker')
    op.drop_table('flights', schema='flights_tracker')
    op.drop_table('expenses', schema='expenses_tracker')
    op.drop_index(op.f('ix_core_refresh_tokens_token'), table_name='refresh_tokens', schema='core')
    op.drop_table('refresh_tokens', schema='core')
    op.drop_index('ix_products_name', table_name='products', schema='macro_tracker')
    op.drop_index('ix_products_barcode', table_name='products', schema='macro_tracker', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.drop_table('products', schema='macro_tracker')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    # ### end Alembic commands ###
