"""add calendar tracker

Revision ID: c92cac1ce388
Revises: 787b241dff5d
Create Date: 2026-03-06 19:27:39.962913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c92cac1ce388'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('default_enable_dnd', sa.Boolean(), nullable=False),
    sa.Column('default_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_categories_id'), 'categories', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_categories_user_id'), 'categories', ['user_id'], unique=False, schema='calendar_tracker')
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False, schema='calendar_tracker')
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'DONE', name='reminderstatus', schema='calendar_tracker'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='reminderpriority', schema='calendar_tracker'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['calendar_tracker.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_reminders_id'), 'reminders', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_reminders_user_id'), 'reminders', ['user_id'], unique=False, schema='calendar_tracker')
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rrule', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('enable_dnd', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['calendar_tracker.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_routines_id'), 'routines', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_routines_user_id'), 'routines', ['user_id'], unique=False, schema='calendar_tracker')
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('color_override', sa.String(length=7), nullable=True),
    sa.Column('enable_dnd', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('google_event_id', sa.String(length=200), nullable=True),
    sa.Column('apple_event_id', sa.String(length=200), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['calendar_tracker.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reminder_id'], ['calendar_tracker.reminders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['calendar_tracker.routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_events_id'), 'events', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_events_user_id'), 'events', ['user_id'], unique=False, schema='calendar_tracker')
    op.create_table('routine_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('action', sa.Enum('CANCELLED', 'MODIFIED', name='routineexceptionaction', schema='calendar_tracker'), nullable=False),
    sa.Column('new_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_title', sa.String(length=200), nullable=True),
    sa.Column('new_enable_dnd', sa.Boolean(), nullable=True),
    sa.Column('new_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['calendar_tracker.routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_routine_exceptions_id'), 'routine_exceptions', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_routine_exceptions_routine_id'), 'routine_exceptions', ['routine_id'], unique=False, schema='calendar_tracker')
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_tracker.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar_tracker'
    )
    op.create_index(op.f('ix_calendar_tracker_notifications_id'), 'notifications', ['id'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_notifications_trigger_at'), 'notifications', ['trigger_at'], unique=False, schema='calendar_tracker')
    op.create_index(op.f('ix_calendar_tracker_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='calendar_tracker')

    # Enum type corrections — USING clause required for existing columns
    op.alter_column('expenses', 'account',
               existing_type=postgresql.ENUM('REVOLUT', 'IMAGIN', name='expensecategory', schema='expenses_tracker'),
               type_=sa.Enum('REVOLUT', 'IMAGIN', name='expensecategory'),
               existing_nullable=False,
               postgresql_using='account::text::expensecategory',
               schema='expenses_tracker')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses', schema='expenses_tracker')
    op.drop_index(op.f('ix_body_measurements_id'), table_name='body_measurements', schema='gym_tracker')
    op.alter_column('exercises', 'exercise_type',
               existing_type=postgresql.ENUM('Cardio', 'Weight_reps', 'Bodyweight', name='gymsettype', schema='gym_tracker'),
               type_=sa.Enum('Cardio', 'Weight_reps', 'Bodyweight', name='gymsettype'),
               existing_nullable=False,
               postgresql_using='exercise_type::text::gymsettype',
               schema='gym_tracker')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises', schema='gym_tracker')
    op.drop_index(op.f('ix_sets_id'), table_name='sets', schema='gym_tracker')
    op.drop_index(op.f('ix_workout_muscle_groups_id'), table_name='workout_muscle_groups', schema='gym_tracker')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts', schema='gym_tracker')
    op.drop_index(op.f('ix_travels_photos_favorites'), table_name='photos', schema='travels_tracker')
    op.drop_index(op.f('ix_travels_photos_trip_status'), table_name='photos', schema='travels_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_travels_photos_trip_status'), 'photos', ['trip_id', 'status'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_travels_photos_favorites'), 'photos', ['user_id', 'is_favorite'], unique=False, schema='travels_tracker')
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False, schema='gym_tracker')
    op.create_index(op.f('ix_workout_muscle_groups_id'), 'workout_muscle_groups', ['id'], unique=False, schema='gym_tracker')
    op.create_index(op.f('ix_sets_id'), 'sets', ['id'], unique=False, schema='gym_tracker')
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False, schema='gym_tracker')
    op.alter_column('exercises', 'exercise_type',
               existing_type=sa.Enum('Cardio', 'Weight_reps', 'Bodyweight', name='gymsettype'),
               type_=postgresql.ENUM('Cardio', 'Weight_reps', 'Bodyweight', name='gymsettype', schema='gym_tracker'),
               existing_nullable=False,
               postgresql_using='exercise_type::text::gymsettype',
               schema='gym_tracker')
    op.create_index(op.f('ix_body_measurements_id'), 'body_measurements', ['id'], unique=False, schema='gym_tracker')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False, schema='expenses_tracker')
    op.alter_column('expenses', 'account',
               existing_type=sa.Enum('REVOLUT', 'IMAGIN', name='expensecategory'),
               type_=postgresql.ENUM('REVOLUT', 'IMAGIN', name='expensecategory', schema='expenses_tracker'),
               existing_nullable=False,
               postgresql_using='account::text::expensecategory',
               schema='expenses_tracker')
    op.drop_index(op.f('ix_calendar_tracker_notifications_user_id'), table_name='notifications', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_notifications_trigger_at'), table_name='notifications', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_notifications_id'), table_name='notifications', schema='calendar_tracker')
    op.drop_table('notifications', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_routine_exceptions_routine_id'), table_name='routine_exceptions', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_routine_exceptions_id'), table_name='routine_exceptions', schema='calendar_tracker')
    op.drop_table('routine_exceptions', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_events_user_id'), table_name='events', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_events_id'), table_name='events', schema='calendar_tracker')
    op.drop_table('events', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_routines_user_id'), table_name='routines', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_routines_id'), table_name='routines', schema='calendar_tracker')
    op.drop_table('routines', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_reminders_user_id'), table_name='reminders', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_reminders_id'), table_name='reminders', schema='calendar_tracker')
    op.drop_table('reminders', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_fcm_tokens_user_id'), table_name='fcm_tokens', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_fcm_tokens_id'), table_name='fcm_tokens', schema='calendar_tracker')
    op.drop_table('fcm_tokens', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_categories_user_id'), table_name='categories', schema='calendar_tracker')
    op.drop_index(op.f('ix_calendar_tracker_categories_id'), table_name='categories', schema='calendar_tracker')
    op.drop_table('categories', schema='calendar_tracker')
    # ### end Alembic commands ###