"""add automations engine

Revision ID: ec870a2cc78e
Revises: c92cac1ce388
Create Date: 2026-03-06 21:34:09.605254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec870a2cc78e'
down_revision: Union[str, Sequence[str], None] = 'c92cac1ce388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('flow', sa.JSON(), nullable=False),
    sa.Column('trigger_type', sa.Enum('MODULE_EVENT', 'WEBHOOK', 'CRON', name='automationtriggertype', schema='automations'), nullable=False),
    sa.Column('trigger_ref', sa.String(length=200), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='automations'
    )
    op.create_index(op.f('ix_automations_automations_id'), 'automations', ['id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_automations_user_id'), 'automations', ['user_id'], unique=False, schema='automations')
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='automations'
    )
    op.create_index(op.f('ix_automations_api_keys_id'), 'api_keys', ['id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_api_keys_user_id'), 'api_keys', ['user_id'], unique=False, schema='automations')
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='executionstatus', schema='automations'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('node_logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='automations'
    )
    op.create_index(op.f('ix_automations_executions_automation_id'), 'executions', ['automation_id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_executions_id'), 'executions', ['id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_executions_user_id'), 'executions', ['user_id'], unique=False, schema='automations')
    op.create_table('webhooks_inbound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='automations'
    )
    op.create_index(op.f('ix_automations_webhooks_inbound_automation_id'), 'webhooks_inbound', ['automation_id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_webhooks_inbound_id'), 'webhooks_inbound', ['id'], unique=False, schema='automations')
    op.create_index(op.f('ix_automations_webhooks_inbound_user_id'), 'webhooks_inbound', ['user_id'], unique=False, schema='automations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automations_webhooks_inbound_user_id'), table_name='webhooks_inbound', schema='automations')
    op.drop_index(op.f('ix_automations_webhooks_inbound_id'), table_name='webhooks_inbound', schema='automations')
    op.drop_index(op.f('ix_automations_webhooks_inbound_automation_id'), table_name='webhooks_inbound', schema='automations')
    op.drop_table('webhooks_inbound', schema='automations')
    op.drop_index(op.f('ix_automations_executions_user_id'), table_name='executions', schema='automations')
    op.drop_index(op.f('ix_automations_executions_id'), table_name='executions', schema='automations')
    op.drop_index(op.f('ix_automations_executions_automation_id'), table_name='executions', schema='automations')
    op.drop_table('executions', schema='automations')
    op.drop_index(op.f('ix_automations_api_keys_user_id'), table_name='api_keys', schema='automations')
    op.drop_index(op.f('ix_automations_api_keys_id'), table_name='api_keys', schema='automations')
    op.drop_table('api_keys', schema='automations')
    op.drop_index(op.f('ix_automations_automations_user_id'), table_name='automations', schema='automations')
    op.drop_index(op.f('ix_automations_automations_id'), table_name='automations', schema='automations')
    op.drop_table('automations', schema='automations')
    # ### end Alembic commands ###
